CREATE DATABASE PartCenter;
USE PartCenter;
CREATE TABLE Usuarios(
  Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  Nombre VARCHAR(20) NOT NULL,
  Apellido VARCHAR(20) NOT NULL,
  Apodo VARCHAR(20) NOT NULL,
  Cedula VARCHAR(13) NOT NULL,
  IdRangoEdad INT NOT NULL,
  Telefono VARCHAR(15) NOT NULL,
  Email VARCHAR(100),
  Password VARCHAR(100) NOT NULL,
  IdRol INT,
  Fecha DATETIME NOT NULL DEFAULT(GETDATE())
) CREATE TABLE Proyecto(
  Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  Nombre VARCHAR(20) NOT NULL,
  IdUsuario VARCHAR(255)
) CREATE TABLE Comite(
  Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  Nombre VARCHAR(20) NOT NULL,
  IdUsuario VARCHAR(255)
) CREATE TABLE Municipio(
  Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  Nombre VARCHAR(20) NOT NULL,
  IdUsuario VARCHAR(255)
) CREATE TABLE Sector(
  Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  Nombre VARCHAR(20) NOT NULL,
  IdUsuario VARCHAR(255)
) CREATE TABLE Partido(
  Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  Nombre VARCHAR(50) NOT NULL,
  IdUsuario VARCHAR(255)
) CREATE TABLE Rol(
  Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  Nombre VARCHAR(50) NOT NULL,
  IdPartido INT NOT NULL,
  DEFAULT(0),
  IdUsuario VARCHAR(255)
) CREATE TABLE Persona(
  Id INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
  Nombre VARCHAR(20) NOT NULL,
  Apellido VARCHAR(20) NOT NULL,
  Apodo VARCHAR(20) NOT NULL,
  Cedula VARCHAR(13) NOT NULL,
  IdRangoEdad INT NOT NULL,
  Telefono VARCHAR(15) NOT NULL,
  Email VARCHAR(100),
  IdDirigente INT NOT NULL,
  IdPartido INT NOT NULL,
  DEFAULT(0),
  IdRol INT NOT NULL,
  IdComite INT,
  IdMunicipio INT,
  IdSector INT,
  Colegio VARCHAR(50),
  IdUsuario VARCHAR(255),
  Fecha DATETIME NOT NULL DEFAULT(GETDATE())
)