
@api = http://localhost:2000/integrantes


GET {{api}}
###
GET {{api}}/38
###
GET {{api}}/count
###
POST {{api}}
Content-Type: application/json

{
    "title": "Count",
    "description": "Count the 5"
}
###
DELETE  {{api}}/10
###
PUT  {{api}}/10
Content-Type: application/json

{
    "title": "Count",
    "description": "Count the 10"
}